# Use Dependabot to update GitHub Actions
version: 2
updates:

# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updated GitHub Actions every week
    interval: "weekly"
