---
name: "build-docker-image"

on:
  pull_request:

  push:
    tags:
    - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout the repository"
      uses: actions/checkout@v3

    - name: "Extract metadata for the Docker image"
      if: github.event_name == 'push' && github.ref_type == 'tag' # Only extract metadata if we push a tag
      id: metadata_extraction
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}

    - name: "Login to GitHub Container Registry"
      if: github.event_name == 'push' && github.ref_type == 'tag' # Only login if we push a tag
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v3
      with:
        platforms: "linux/amd64,linux/arm64"

    - name: "Build and eventually push container image"
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        tags: ${{ steps.metadata_extraction.outputs.tags }}
        labels: ${{ steps.metadata_extraction.outputs.labels }}
        push: ${{ github.event_name == 'push' && github.ref_type == 'tag' }} # Only push builded image if we push a tag
